[general]

[env]

[window]

[scrolling]

[font]
    normal.family = "Fira Code"
    bold.family = "Fira Code"
    italic.family = "Fira Code"
    bold_italic.family = "Fira Code"
    
[colors]
  [colors.primary]
    background = "#1a1a1a"
    foreground = "#47bf00"
    
  [colors.cursor]
    text = "#191622"
    cursor = "#f8f8f2"
    
  [colors.normal]
    black = "#000000"
    red = "#ff5555"
    green = "#50fa7b"
    yellow = "#effa78"
    blue = "#bd93f9"
    magenta = "#ff79c6"
    cyan = "#8d79ba"
    white = "#bfbfbf"
    
  [colors.bright]
    black = "#4d4d4d"
    red = "#ff6e67"
    green = "#5af78e"
    yellow = "#eaf08d"
    blue = "#caa9fa"
    magenta = "#ff92d0"
    cyan = "#aa91e3"
    white = "#e6e6e6"
    
  [colors.dim]
    black = "#000000"
    red = "#a90000"
    green = "#049f2b"
    yellow = "#a3b106"
    blue = "#530aba"
    magenta = "#bb006b"
    cyan = "#433364"
    white = "#5f5f5f"
    
[bell]
    animation = "EaseOutSine"
    duration = 500

[selection]
  
[cursor]

[terminal]
    
[mouse]
    hide_when_typing = true
    
    
[hints]
  [[hints.enabled]]
    command = "xdg-open" # On Linux/BSD
    hyperlinks = true
    post_processing = true
    persist = false
    mouse.enabled = true
    binding = { key = "O", mods = "Control|Shift" }
    regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
    
[keyboard]

[debug]
